// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_EPcwQnLBhn1ykUhGleMZDtGDKkMY7E',
    appId: '1:755489411255:web:c08bf223287a5a939cfd32',
    messagingSenderId: '755489411255',
    projectId: 'test-firebase-auth-a4cba',
    authDomain: 'test-firebase-auth-a4cba.firebaseapp.com',
    storageBucket: 'test-firebase-auth-a4cba.appspot.com',
    measurementId: 'G-6VV59KX5BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4JmhbndnHFZ9TGGbsy7mAvJNDM4GkBAI',
    appId: '1:755489411255:android:49e68733c6a42fe69cfd32',
    messagingSenderId: '755489411255',
    projectId: 'test-firebase-auth-a4cba',
    storageBucket: 'test-firebase-auth-a4cba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbRLt7V6kerb36lGN1okSDS2JHu48VzG4',
    appId: '1:755489411255:ios:08365e32e40585239cfd32',
    messagingSenderId: '755489411255',
    projectId: 'test-firebase-auth-a4cba',
    storageBucket: 'test-firebase-auth-a4cba.appspot.com',
    iosClientId: '755489411255-f3k8vd37ncd4ecv4u31ovnp79t0htnuh.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.auth.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbRLt7V6kerb36lGN1okSDS2JHu48VzG4',
    appId: '1:755489411255:ios:08365e32e40585239cfd32',
    messagingSenderId: '755489411255',
    projectId: 'test-firebase-auth-a4cba',
    storageBucket: 'test-firebase-auth-a4cba.appspot.com',
    iosClientId: '755489411255-f3k8vd37ncd4ecv4u31ovnp79t0htnuh.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.auth.example',
  );
}
